profile mockup
wyncode/c39_create_and_collab pull request #20
Opened 2020-11-21 17:10 UTC by danchio

2020-11-21 17:14 UTC, LEPII approved these changes

2020-11-21 17:14 UTC, jctlz4 approved these changes

2020-11-22 20:38 UTC, saritasalazar approved these changes

2020-11-22 20:39 UTC, saritasalazar requested changes
Hey! Looks good but it looks like you have some merge conflicts.

2020-11-23 14:43 UTC, saritasalazar approved these changes

2020-11-23 19:07 UTC, wkennedy8 approved these changes

2020-11-23 19:09 UTC, merged